### ISSUE TITLE
Incorrect links in README-TEMPLATE.md

### ISSUE THREAD

**Issue by victoriacheng15** [fharper/coffeechat#35]
Links in `README-TEMPLATE.md` lead to the 404 error page

- people.json and schema.json under `Add yourself to the list`
- people.json under `Remove yourself from this list`

Links should not have `/scripts` in

e.g.
`https://github.com/fharper/coffeechat/blob/main/scripts/people.json`

should be 
`https://github.com/fharper/coffeechat/blob/main/people.json`

**Comment by fharper** [comment]
Good point, I didn't care much as `README-TEMPLATE.md` is used to generate `README.md` which have the right path for `people.json`, but I can make it work for both by putting the full URL instead of just the filename as a path. Thanks :)

**Comment by victoriacheng15** [comment]
Ah, I see! Just wanted to make sure the links are correct in the end! 

TGIF! :D
