### ISSUE TITLE
Possible to link to website/blog from readme?

### ISSUE THREAD

**Issue by softwaredoug** [fharper/coffeechat#53]
Thanks @fharper for this great initiative.

Thanks for linking to LinkedIn. Is it possible to also link to our website we added? It might help people get a sense, scanning my blog, what I might be helpful with.

🙏🏻

**Comment by fharper** [comment]
Yeah, it's in my todo list https://github.com/fharper/coffeechat/issues/26, but I just didn't have the time yet to prioritize that.

PR are always welcome :)
